Update dotnet.yml - containerized test db

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -1,6 +1,3 @@
-# This workflow will build a .NET project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
-
 name: .NET
 
 on:
@@ -10,19 +7,60 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
-
+  test:
     runs-on: ubuntu-latest
+    
+    services:
+      postgres:
+        image: postgres:latest
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: slack_clone_test
+        ports:
+          - 5432:5432
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
 
     steps:
     - uses: actions/checkout@v3
+  
+    - name: Start PostgreSQL Docker container
+      run: |
+        docker run -d \
+          -p 5432:5432 \
+          -e POSTGRES_USER=postgres \
+          -e POSTGRES_PASSWORD=postgres \
+          -e POSTGRES_DB=slack_clone_test \
+          --health-cmd pg_isready \
+          --health-interval 10s \
+          --health-timeout 5s \
+          --health-retries 3 \
+          --name test-postgres \
+          postgres:latest
+
+    - name: Wait for Postgres to be ready
+      run: |
+        timeout=10
+        interval=1
+        while ! docker exec -i "$(docker ps -q -f name=postgres)" pg_isready -U postgres; do
+          sleep $interval
+          timeout=$((timeout - interval))
+          if [[ $timeout -le 0 ]]; then
+            echo "Timeout: PostgreSQL failed to start."
+            exit 1
+          fi
+        done
+    
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 7.0.x
+        
     - name: Restore dependencies
       run: dotnet restore
+      
     - name: Build
       run: dotnet build --no-restore --configuration Release
+      
     - name: Test
       run: dotnet test --no-build --verbosity normal --configuration Release
